# Generated by Django 4.2.3 on 2023-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day1', models.IntegerField(default=0)),
                ('day2', models.IntegerField(default=0)),
                ('day3', models.IntegerField(default=0)),
                ('day4', models.IntegerField(default=0)),
                ('day5', models.IntegerField(default=0)),
                ('day6', models.IntegerField(default=0)),
                ('day7', models.IntegerField(default=0)),
                ('day8', models.IntegerField(default=0)),
                ('day9', models.IntegerField(default=0)),
                ('day10', models.IntegerField(default=0)),
                ('day11', models.IntegerField(default=0)),
                ('day12', models.IntegerField(default=0)),
                ('day13', models.IntegerField(default=0)),
                ('day14', models.IntegerField(default=0)),
            ],
        ),
    ]
