# Generated by Django 4.2 on 2023-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margoBookLength', models.IntegerField()),
                ('romaBookLength', models.IntegerField()),
                ('dateOfStart', models.DateField()),
            ],
        ),
    ]
