# Generated by Django 4.2 on 2023-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_configdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configdata',
            name='dateOfStart',
            field=models.DateField(blank=True),
        ),
    ]
